### ISSUE TITLE
Netlify Deploy error

### ISSUE THREAD

**Issue by tiborbokor** [EmielH/hallo-hugo#21]
Hi! :)
If Deploy with Netlify, error messages, and no deploy Site.
My repo: https://github.com/tiborbokor/hallo-hugo

Howto install this theme? What is problem? 

Error messages: 
https://pastebin.com/wySPSJ3q

Thanks!

**Comment by EmielH** [comment]
Hi @tiborbokor, personally I've never used Netlify, so I can't really help troubleshoot. There is a clue in the logfile:

```
5:43:03 PM: $ hugo server -t hallo
5:43:05 PM: Error: Unable to find theme Directory: /opt/build/repo/themes/hallo
```

I guess the theme hasn't been installed correctly for usage on Netlify. That's the closest guess I can make without any knowledge about Netlify. Hope it helps nevertheless!

**Comment by tiborbokor** [comment]
Thanks for the help. :)
What should I use to work well?

**Comment by EmielH** [comment]
My guess is that something in the Netlify configuration needs to be changed so that the theme is loaded correctly. I guess that you'd get the same error with a different theme. Unfortunately, as I said, I don't know anything about Netlify. The best place to ask for help in this matter is the [Hugo forum](https://discourse.gohugo.io/). Good luck! Sorry I can't help any further in this matter...

If it turns out to be a bug in the theme after all, feel free to let me know and I can have a look!

**Comment by tiborbokor** [comment]
Thank you! 👍
